id: A9F338790
title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed Instructions'
type: translation
pechas:
- I9C669148
- I1A989324
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:44:01.756323
  last_modified_at: 2023-01-04 12:44:01.756345
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I9C669148/1A0A: DB2F
  I1A989324/17B2: DB2F
